# Generated by Django 2.0.4 on 2018-04-25 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='state',
        ),
        migrations.AddField(
            model_name='cell',
            name='modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_games', to='users.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='num_players',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='game',
            name='waiting_to_finish_turn',
            field=models.IntegerField(default=8),
        ),
    ]
