# Generated by Django 2.0.4 on 2018-04-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180425_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cells_owned', to='users.Player_Profile'),
        ),
    ]
