# Generated by Django 2.0.3 on 2018-04-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_cell_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_profile',
            name='move',
            field=models.CharField(default='00', max_length=255),
        ),
    ]
