<<<<<<< HEAD
# Generated by Django 2.0.4 on 2018-04-26 21:34
=======
# Generated by Django 2.0.3 on 2018-04-26 21:34
>>>>>>> fc7349903c8ac0e4311b734eefc76f7335af2053

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_cell_neighbors'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='spawn_locations',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
